### ISSUE TITLE
How to create newlines in generated Markdown?

### ISSUE THREAD

**Issue by antropez** [nereusx/md2roff#1]
Absolutely love this, but one issue I came across is the ability to generate newlines in the generated Markdown. Is that supported? I cannot find anything like it in the documentation, even after messing around with 'COMMAND' which seemed kind of confusing.

**Comment by nereusx** [comment]
md2roff convert markdown documents to man-pages (and other roff formats).
Leave an empty line and should converted to .P in roff file. Another way is to use code block so you can control it more easily.

Internal commands, COMMAND & SYNTAX works but no needed anymore since you can pass as option the style of SYNOPSIS SECTION.

+++++ from man page +++++
OPTIONS
  -pX, --synopsis-style=X
       For man-page only. specify the style of the SYNOPSIS. Where X, 
      0 = default, 1 = md2roff highlight, 2 =.SY/.OP commands, 3 =.Nm commands.
+++++
Use -p1 for better results. Use -p2 for better compatibility in linux systems. Use -p3 for BSD. Still -p1 should be works nice and better in all cases.

See md2roff.md, this file generates the md2roff man page.
This is how md2roff man page created from md2roff.md:
```
# create man page
md2roff --synopsis-style=1 md2roff.md > md2roff.1
# create PDF file from man-page
groff md2roff.1 -Tpdf -man -P -e > md2roff.1.pdf 
# gzip man page
gzip -f md2roff.1
```

**Comment by antropez** [comment]
Alright, thanks!
